### ISSUE TITLE
Only three supported locales?

### ISSUE THREAD

**Issue by tylordippel** [blakeembrey/lower-case#3]
Hi Blake,

Quick question. It looks like you have only supported 3 locales. Are those the only locales where the case mapping are different and for all other languages the normal toLowerCase will suffice (which I see is what your code does anyways)? I just wanted to make sure that I could use your module reliably for locales other than az, tr, and lt.

Thanks!

**Comment by blakeembrey** [comment]
Correct, all locales can be correctly handled with `toLowerCase` (upper case and lower case are completely different alphabets) and the only overrides are the languages which conflict. Of course, I don't speak and write in dozens of languages, this was based on my own research - if something appears to be off, open an issue 👍
